### ISSUE TITLE
Implement the `Click2Run` command

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurecontainerapps#425]
Create a workspace command that allows a user to deploy their workspace project to ACA, while providing a minimal number of prompts/configurations for easy deployment.  We will leverage the ACR tasks method for deploying new images.  Project will require a `Dockerfile` to deploy.

**Todo**:
- [x] Determine which values can be defaulted/assumed (Team - 8/10)
- [x] Enable creating an Azure Container Registry if the user doesn't already have one available (@motm32)
- [ ] Implement the command/contract (@MicroFish91)

**Comment by MicroFish91** [comment]
Update: First iteration will assume all resources need to be created from scratch.  A future iteration may include saving values as local project settings to save time for repeat deployments.  Also possible future iteration may include a `basic` vs `advanced` version of this command.

**Comment by MicroFish91** [comment]
For creating a new ACR, this is relevant:
https://github.com/microsoft/vscode-azurecontainerapps/issues/78

We need to keep in mind that in some cases we are pushing images, and in other situations we are pulling images and design around those needs accordingly.
