### ISSUE TITLE
Monorepo: Expand support for deploying multiple app configurations within the same workspace project

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurecontainerapps#607]
**I. Overview**

At the current time we only support saving & deploying from one workspace app configuration.  To support saving and deploying from multiple app configurations, we need to migrate to a new schema and add additional capabilities as shown below.

**II. Flow**
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/d5e60ff3-a7b3-4ad6-b03f-8ec14f389860)

**III. Schema**

Old:
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/9fa0b585-cdd9-4641-8cae-0c2b75518525)

New:
<img src="https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/e823cfaa-a87d-4d1d-80f6-8026515172fc" width="400px">

**IV. Work Items**

Deploy Project from Workspace (internal):
- [x] [Add support for taking an existing `envPath` and converting it to environment variables on the CA envelope](https://github.com/microsoft/vscode-azurecontainerapps/issues/640)
- [x] [Update the settings save logic to abide by the new schema](https://github.com/microsoft/vscode-azurecontainerapps/issues/608)
- [x] [Update default resource naming logic](https://github.com/microsoft/vscode-azurecontainerapps/issues/611)
- [x] [Decouple settings validation and parsing logic from `deployWorkspaceProjectInternal`](https://github.com/microsoft/vscode-azurecontainerapps/issues/610)

Monorepo:
- [x] [Add hover descriptions for the new json schemas](https://github.com/microsoft/vscode-azurecontainerapps/issues/645)
- [x] [Add ability to detect and convert old schema to new schema](https://github.com/microsoft/vscode-azurecontainerapps/issues/612) **(In Review)**
- [x] [Monorepo core logic](https://github.com/microsoft/vscode-azurecontainerapps/issues/613) 
See linked issue for additional task breakdown.
- [x] [Telemetry](https://github.com/microsoft/vscode-azurecontainerapps/issues/636)

Finishing touches (added 3/26):
- [x] Better default naming convention for each resource (e.g. `-rg`, `-me`, `-ca`)
- [x] Try to default container registry when a tree item is provided
- [x] Also try to default a container registry within the internal logic if one still hasn't been provided
- [x] Don't show a dropdown for loading workspace configuration in activity log if no children provided
- [x] Flat-list all the activity log items for the resource verification steps
- [ ] Provide a good test repo for CTI
- [ ] Engineering: Revisit/document step priority levels in a way that makes sense

Dilithium:
- [ ] Tests

TBD:
- [ ] Reconfiguring existing settings before deployment
- [ ] More streamlined path for existing container app project integration
- [ ] Update the activity log API to accept an option indicating whether to auto-expand a top-level activity node without user input and utilize in the deployment configuration logic for monorepo
